name: selectable_box
description: A flutter package that will allow you to create a selectable box with multiple customizations.
version: 1.0.4
homepage: https://github.com/mantreshkhurana/selectable_box
repository: https://github.com/mantreshkhurana/selectable_box

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  figma_squircle: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true